theme = "monokai_vox"

[editor]
shell = ["nu", "-c"]
line-number = "relative"
cursorline = true
color-modes = true
true-color = true
bufferline = "always"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.indent-guides]
render = true
character = "|"

[editor.soft-wrap]
enable = true

[keys.normal]
"C-i" = "jump_forward"
"_" = "@:"

[keys.insert]
"C-b" = "move_char_left"
"C-f" = "move_char_right"
"A-b" = "move_prev_word_start"
"A-f" = "move_next_word_start"
"C-p" = "move_line_up"
"C-n" = "move_line_down"
"C-a" = "goto_line_start"
"C-s" = "goto_first_nonwhitespace"
"C-e" = "goto_line_end_newline"

[keys.normal.space.w]
"E" = "swap_view_up"
"N" = "swap_view_down"
"M" = "swap_view_left"
"I" = "swap_view_right"
"e" = "jump_view_up"
"n" = "jump_view_down"
"m" = "jump_view_left"
"i" = "jump_view_right"

[editor.search]
smart-case = false
