# Rust
[language-server.rust-analyzer.config]
check.command = "clippy"

# C-sharp
[[language]]
name = "c-sharp"
scope = "source.csharp"
injection-regex = "c-?sharp"
file-types = ["cs", "csx", "cake"]
roots = ["sln", "csproj"]
indent = { tab-width = 4, unit = "    " }
auto-format = true

[language-server.omnisharp]
timeout = 10000

# Typst
[language-server.tinymist]
command = "tinymist"

[[language]]
name = "typst"
language-servers = ["tinymist"]
formatter = { command = "typstyle" }
auto-format = true
